#services:
#  db:
#    image: postgres:16
#    container_name: mini-ecommerce-db
#    environment:
#      POSTGRES_DB: mini_shop
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  app:
#    build: .
#    container_name: mini-ecommerce-app
#    depends_on:
#      - db
#    env_file:
#      - .env
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mini_shop
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "8085:8085"
#
#volumes:
#  pgdata:


services:
  db:
    image: postgres:16
    container_name: mini-ecommerce-db
    environment:
      POSTGRES_DB: mini_shop
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d mini_shop"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: mini-ecommerce-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mini_shop
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8085/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata: